### ISSUE TITLE
Hitting the Enter key while focus is in the todo text box should start a new todo

### ISSUE THREAD

**Issue by toxoplasmotic** [SeanECogan/todo-it#3]
This would prevent me from having to move my hand to the mouse in order to add more than one item at a time.

Note that hitting Enter while focus is on an empty todo text box should NOT start a new todo.

**Comment by SeanECogan** [comment]
I had toyed around with this idea, and wasn't sure if it was too aggressive to create a new one automatically. But, after having used it a bit, I think it's definitely a good suggestion.

**Comment by SeanECogan** [comment]
Issue has been resolved with PR #9.
